#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PalabrasEnredadas.Resource", IsApplication=true)]

namespace PalabrasEnredadas
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.93")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F010000
			public const int cw_StartGame_btn = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int cw_title_tv = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int cw_wordsInput_et = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int cw_words_lv = 2130771971;
			
			// aapt resource value: 0x7F010006
			public const int g_allWords_tv = 2130771974;
			
			// aapt resource value: 0x7F010004
			public const int g_Matrix_tl = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int g_Solve_btn = 2130771973;
			
			// aapt resource value: 0x7F010008
			public const int myButton = 2130771976;
			
			// aapt resource value: 0x7F010007
			public const int m_title_tv = 2130771975;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F020000
			public const int ChooseWords = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Game = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int Main = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040008
			public const int app_name = 2130968584;
			
			// aapt resource value: 0x7F040000
			public const int ChooseWords_Hint = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ChooseWords_SearchBarTitle = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ChooseWords_StartButton = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ChooseWords_Title = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ChooseWords_Words = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int GameTest = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int Game_Solve_Button = 2130968582;
			
			// aapt resource value: 0x7F040009
			public const int hello = 2130968585;
			
			// aapt resource value: 0x7F040007
			public const int Main_StartGame_Btn = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
